### ISSUE TITLE
Add port 80 and 443 with web and websecure

### ISSUE THREAD

**Issue by mattthhdp** [santimar/traefik-home#29]
Im not at home right now but, should be pretty easy to add. i will also look if it's possible to check into the traefiks rules added manually . this would be perfect for my use case.
```
                {{ $entrypoint_label := print "traefik.http.routers." $service_name ".entrypoints" }}
                {{ $entrypoint := index $container.Labels $entrypoint_label }}
                {{ $protocol := "" }}
                {{ if eq $entrypoint "websecure" }}
                    {{ $protocol = "https" }}
                {{ else if eq $entrypoint "443" }}
                    {{ $protocol = "http" }}
                {{ else if eq $entrypoint "web" }}
                    {{ $protocol = "http" }}
                {{ else if eq $entrypoint "web" }}
                    {{ $protocol = "80" }}
                {{ else }}
                    {{/* entrypoint not supported */}}
                    {{continue}}
                {{ end }}
```

**Comment by santimar** [comment]
I am not sure about your problem.
In traefik you have to declare an entrypoint with a given name. 
`web` and `websecure` entrypoint are usually defined if you want to serve http or https traffic.
did you define a custom entrypoint named `443` instead of using `websecure`?

**Comment by mattthhdp** [comment]
Here is the beginning of my traefik 
![image](https://user-images.githubusercontent.com/10604324/219236092-03dcc09f-28f1-423e-a7d7-b2adf3327e38.png)

i was following this guide so that' why i am asking 
https://www.smarthomebeginner.com/traefik-docker-compose-guide-2022/#Traefik_Reverse_Proxy_Overview

**Comment by santimar** [comment]
ok, now i understand.
on the official guide (https://doc.traefik.io/traefik/routing/entrypoints/#configuration-examples) they define the `web` and `websecure` entrypoint, so i used them.
you can rename your entrypoint from `http` and `https` to `web` and `websecure` and traefik-home will work.
you shouldn't have any problem with this change.

the problem here is that you can name your entrypoint the way you want
for a more general purpose solution, i should find the traefik container, find the `entrypoints.*` labels and then find the ones with `.address=:80` and `.address=:443`
the way the project works, makes it a bit hard to accomplish
i do not see other solution right now

**Comment by mattthhdp** [comment]
Everything work as it should with your modification! Nice
