### ISSUE TITLE
Open in new tabs options instead of change page ?

### ISSUE THREAD

**Issue by mattthhdp** [santimar/traefik-home#30]
Maybe add the option ?

**Comment by santimar** [comment]
Hi @mattthhdp I've set the links to open on the same tab since this is the default link behavior.
If you want to open a link in a new tab you can wheel-click or right-click on the link and it will open on a new tab.
I feel the majority of people using traefik-home (including myself) are using it as a start page to access other services and forget about it.

Anyway if you prefer to have a behavior where link are always opened on new tab, I can add the option.
It should be really easy to implement.
Let me know

**Comment by mattthhdp** [comment]
Working as it should !
Thank you again !
