### ISSUE TITLE
Possibility to display entries from dynamic.yaml

### ISSUE THREAD

**Issue by M1scer** [santimar/traefik-home#68]
It would be cool if you could also display entries from dynamic.yaml.

I have several devices such as routers, printers, scanners, vacuum cleaners, ... to which I have assigned a URL via dynamic.yaml. 
It would be cool if you could also display these directly.

**Comment by santimar** [comment]
I'm not totally sure about what you're asking here.

Can you provide more info and a minimal example of a `dynamic.yaml`?
Thanks

**Comment by M1scer** [comment]
My idea is that all routers / services that are routed via Traefik are also displayed in Traefik Home.

Some routers are not defined directly via Docker labels but via a file. These routers are currently not found because Traefik Home only looks at the labels.
See Traefik Docs: 
https://doc.traefik.io/traefik/providers/file/

There are also examples as .yaml or .toml file.

**Comment by santimar** [comment]
Ok, got it.

Personally I think that this feature doesn't fit well here since `traefik-home` works using labels provided by docker.

In order to support this, one would need to bind mount the config file (and maybe more than one) to the container app and parse it.
The structure to parse will be quite different, since we would read a configuration yaml file instead of the json response provided by `docker-gen`

I'm not even sure we can read files using `docker-gen` template engine.

**Comment by M1scer** [comment]
it would also be possible to read all the routers via the api:
http://localhost:8080/api/http/routers

Instead of the docker labels, reading the api would allow to read all the routers defined in traefik.

**Comment by santimar** [comment]
I've considered it too, but:
1. Traefik API is not enabled by default
2. It will expose sensitive data so you have to either protect it via authentication or to expose it only on the container network
3. The get the data you need to perform a web request (i'm not sure you can do this using docker-gen) and parse the response which is a JSON and needs a completely different parsing

To take advantage of the API probably the project will need a complete refactor and i'm not sure it's worth.
